name: BedrockTridents
version: '1.1.1'
main: me.solitude.bedrocktridents.Main
api-version: '1.21'
description: Adds bedrock functionality to Tridents with Impaling enchantment
commands:
  bedrocktridentsreload:
    description: Reloads config file
    usage: /bedrocktridentsreload
    permission: bedrocktridents.reload
    aliases: [btr]

permissions:
  bedrocktridents.reload:
    description: Allows use of the reload command
    default: op